default: MainClass.class FieldDecimal.class RandomCharacterFromSet.class RandomCharacterRandom.class UIInterface.class UIFormatterFancyCLI.class UIFormatterPlainCLI.class Solution.class
	java MainClass

FieldDecimal.class: FieldDecimal.java
	javac FieldDecimal.java
	
RandomCharacterFromSet.class: RandomCharacterFromSet.java
	javac RandomCharacterFromSet.java
RandomCharacterRandom.class: RandomCharacterRandom.java
	javac RandomCharacterRandom.java
	
UIInterface.class: UIInterface.java
	javac UIInterface.java
UIFormatterFancyCLI.class: UIFormatterFancyCLI.java
	javac UIFormatterFancyCLI.java
UIFormatterPlainCLI.class: UIFormatterPlainCLI.java
	javac UIFormatterPlainCLI.java
	
Solution.class: Solution.java
	javac Solution.java
	

MainClass.class: MainClass.java
	javac MainClass.java