default: MainClass.class FieldDecimal.class RandomCharacterFromSet.class RandomCharacterRandom.class UIInterface.class UIAltInterface.class UIBadInterface.class UIFormatterFancyCLI.class UIFormatterPlainCLI.class UIFormatterBadCLI.class Solution.class
	java MainClass

FieldDecimal.class: FieldDecimal.java
	javac FieldDecimal.java
	
RandomCharacterFromSet.class: RandomCharacterFromSet.java
	javac RandomCharacterFromSet.java
RandomCharacterRandom.class: RandomCharacterRandom.java
	javac RandomCharacterRandom.java
	
UIInterface.class: UIInterface.java
	javac UIInterface.java
UIAltInterface.class: UIAltInterface.java
	javac UIAltInterface.java
UIBadInterface.class: UIBadInterface.java
	javac UIBadInterface.java
	
UIFormatterFancyCLI.class: UIFormatterFancyCLI.java
	javac UIFormatterFancyCLI.java
UIFormatterPlainCLI.class: UIFormatterPlainCLI.java
	javac UIFormatterPlainCLI.java
UIFormatterBadCLI.class: UIFormatterBadCLI.java
	javac UIFormatterBadCLI.java
	
Solution.class: Solution.java
	javac Solution.java
	

MainClass.class: MainClass.java
	javac MainClass.java